// src/lib/components/admin/ImageCard.svelte
<script lang="ts">
  import { getImageName } from "$lib/utils/images";

  export let image = null;
  export let onClick = () => {};
</script>

<div class="img-card" on:click={onClick}>
  <div class="img-container">
    <img src={image} />
  </div>

  <div
    class="img-name flex w-full h-auto bg-white flex justify-center items-center"
  >
    {getImageName(image)}
  </div>
</div>

<style>
  .img-card {
    dispaly: flex;
    flex-direction: column;
    border: 2px solid rgb(223, 223, 227);
    border-radius: 5px;
    cursor: pointer;
    border-radius: 5px;
    height: 230px;
  }

  .img-container {
    height: 160px;
    background-color: rgb(242, 242, 242);
    background-size: 16px 16px;
    background-position: 0px 0px, 8px 8px;
    background-image: linear-gradient(
        45deg,
        rgb(230, 230, 230) 25%,
        transparent 25%,
        transparent 75%,
        rgb(230, 230, 230) 75%,
        rgb(230, 230, 230)
      ),
      linear-gradient(
        45deg,
        rgb(230, 230, 230) 25%,
        transparent 25%,
        transparent 75%,
        rgb(230, 230, 230) 75%,
        rgb(230, 230, 230)
      );

    border-bottom: 2px solid rgb(223, 223, 227);
  }

  .img-container > img {
    width: 100%;
    height: 160px;
    object-fit: contain;
  }

  .img-name {
    height: 66px;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
  }
</style>

// src/components/admin/Cards/ImageCard.tsx
import { getImageName } from "src/utils/images";
import styles from "./ImageCard.module.css";

interface ImageCardProps {
  image: string;
  onClick: VoidFunction;
}

export const ImageCard: React.FC<ImageCardProps> = ({ image, onClick }) => (
  <div className={styles["img-card"]} onClick={onClick}>
    <div className={styles["img-container"]}>
      {/* // eslint-disable-next-line @next/next/no-img-element */}
      <img src={image} width="100%" height="160px" alt="image" />
    </div>

    <div
      className={`${styles["img-name"]} p-2 flex w-full h-auto bg-white flex justify-center items-center`}
    >
      {getImageName(image)}
    </div>
  </div>
);
