// src/components/admin/Forms/TrusteeForm.tsx
import { Controller, useForm } from "react-hook-form";
import { Trustee } from "@/types/global";
import { isValidDescription } from "@/utils/validators";
import { LoadingSpinner } from "../LoadingSpinner";
import { Input } from "../Input";
import { Editor } from "../Editor";

interface TrusteeFormProps {
  className?: string;
  trustee?: Trustee;
  pending?: boolean;
  onSaveTrustee: (trustee: Trustee) => void;
}

const DEFAULT_TRUSTEE: Trustee = {
  name: "",
  description: "",
};

export const TrusteeForm: React.FC<TrusteeFormProps> = ({
  trustee = DEFAULT_TRUSTEE,
  pending,
  onSaveTrustee,
}) => {
  const {
    register,
    control,
    handleSubmit,
    formState: { isDirty, errors, isValid },
  } = useForm<Trustee>({
    defaultValues: { ...trustee },
  });

  return (
    <form
      className="flex flex-col w-full"
      onSubmit={handleSubmit(onSaveTrustee)}
    >
      <div className="flex mb-8 w-full">
        <Input
          register={register}
          options={{ required: "Please add a postcode" }}
          error={errors.name}
          label="Name"
          name="name"
          type="text"
          placeholder="John Doe"
        />
      </div>

      <div className="flex flex-col mb-8 w-full">
        <label className="uppercase block text-gray-700 text-sm font-bold mb-2">
          Description
        </label>
        <div className="h-24">
          <Controller
            control={control}
            name="description"
            rules={{ validate: isValidDescription }}
            render={({ field: { onBlur, onChange, value } }) => (
              <Editor
                value={value}
                error={errors?.description as any}
                onChange={onChange}
                onBlur={onBlur}
              />
            )}
          />
        </div>
      </div>

      <div className="flex items-center border-t-2 border-slate-300 pt-4 h-24">
        <button
          className="btn-admin btn-primary mr-4"
          type="submit"
          // disabled={pending || !isValid || !isDirty}
          disabled={pending || !isValid || !isDirty}
        >
          {pending ? <LoadingSpinner /> : "Save Trustee"}
        </button>
      </div>
    </form>
  );
};

// src/lib/components/admin/Forms/TrusteeForm/TrusteeForm.svelte
<script lang="ts">
  import LoadingSpinner from "$lib/components/shared/LoadingSpinner.svelte";
  import Editor from "$lib/components/admin/FormComponents/TextEditor/Editor.svelte";
  import TextInput from "$lib/components/admin/FormComponents/TextInput.svelte";
  import AlertErrorBox from "$lib/components/admin/shared/AlertErrorBox.svelte";
  import { trusteeSchema } from "./validators";
  import { saveEvent } from "./helpers";

  export let trustee = null;
  export let pending = false;
  export let onSaveTrustee = (): void => {};

  let error = undefined;

  trustee.subscribe((data) => {
    try {
      trusteeSchema.validateSync(data);
      error = undefined;
    } catch (err) {
      error = err.message;
    }
  });

  $: actionsDisabled = error !== undefined;
</script>

<div class="flex flex-col">
  <div class="flex mb-8">
    <TextInput
      bind:value={$trustee.name}
      label="name"
      name="name"
      placeholder="Name"
    />
  </div>

  <div class="mb-8">
    <span class="uppercase block text-gray-700 text-sm font-bold mb-2">
      Description
    </span>
    <Editor bind:content={$trustee.description} />
  </div>

  <div class="flex items-center border-t-2 border-slate-300 pt-4 h-24">
    <button
      class="btn-admin btn-primary mr-4"
      disabled={actionsDisabled | pending}
      on:click={onSaveTrustee}
    >
      {#if pending}
        <LoadingSpinner />
      {:else}
        Save Trustee
      {/if}
    </button>

    {#if error !== undefined}
      <AlertErrorBox {error} />
    {/if}
  </div>
</div>
