// src/routes/admin/products/[id].svelte
<script context="module">
  export const ssr = false;
</script>

<script lang="ts">
  import { page } from "$app/stores";
  import { goto } from "$app/navigation";
  import { fetchJson } from "$lib/utils/fetch-json";
  import { user } from "$lib/stores/user";
  import { onMount } from "svelte";
  import { writable } from "svelte/store";
  import { notifications } from "$lib/stores/notifications";
  import Panel from "$lib/components/admin/Panel.svelte";
  import LoadingSpinner from "$lib/components/shared/LoadingSpinner.svelte";
  import ProductForm from "$lib/components/admin/Forms/ProductForm/ProductForm.svelte";
  import { updateProduct } from "$lib/components/admin/Forms/ProductForm/helpers";

  let productData = null;
  let loading = false; // track the initial load
  let pending = false; // track the product update
  const id = $page.params.id;
  let error = false;

  let product = writable();

  $: token = $user !== null ? $user.access_token : null;

  onMount(async () => {
    const res = await fetchJson(`/admin-products?id=${id}`, { token });

    product.set(res.product);
    loading = false;
  });

  product.subscribe((data) => {
    productData = data;
  });

  async function onSaveProduct() {
    pending = true;
    try {
      await updateProduct({ id, productData, status, token });
      notifications.success(
        {
          title: "Product Updated",
          text: "Your product has been sucessfully updated!",
        },
        3000
      );

      setTimeout(() => {
        goto("/admin/products");
      }, 500);
    } catch (err) {
      error = true;
      notifications.danger(
        {
          title: "An error occurred",
          text: "Your product could not be updated, please try again later or contact the web admin.",
        },
        5000
      );
    }

    pending = false;
    product = null;
  }
</script>

<div class="p-4">
  <div class="flex flex-col sm:w-full xl:w-8/12">
    <div class="flex justify-between items-center w-100">
      <h2 class="text-gray-600 font-bold">Update Product</h2>
      <a href="/admin/products" class="text-black">Go Back</a>
    </div>

    <div class="mt-4 w-100">
      {#if loading}
        <LoadingSpinner />
      {:else if productData}
        <Panel class="w-100">
          <ProductForm {pending} {product} {onSaveProduct} />
        </Panel>
      {/if}
    </div>
  </div>
</div>

// pages/admin/products/[id].tsx
import type { NextPage } from "next";
import { ReactElement, useEffect } from "react";
import { toast } from "react-toastify";
import { useRouter } from "next/router";
import { useAuth } from "@/contexts/AuthContext";
import { AdminLayout } from "layouts/AdminLayout";
import { LoadingSpinner } from "@/components/admin/LoadingSpinner";
import { ProductForm } from "@/components/admin/Forms/ProductForm";
import { useNetlifyGetFunction } from "@/hooks/useNetlifyGetFunction";
import { useNetlifyPutFunction } from "@/hooks/useNetlifyPutFunction";
import { Panel } from "@/components/admin/Panel";
import { Product } from "@/types/global";

interface EditProps {
  id: string;
}

const Edit: React.FC<EditProps> = ({ id }) => {
  const { user } = useAuth();
  const router = useRouter();

  const { data, loading, error } = useNetlifyGetFunction<{ product: Product }>({
    fetchUrlPath: `/admin-products?id=${id}`,
    user,
  });

  const {
    onUpdate,
    pending,
    error: updateError,
  } = useNetlifyPutFunction<{ product: Product }>({ user });

  const onEditProduct = async (updatedProduct: Product) => {
    const res = await onUpdate(`/admin-products?id=${id}`, {
      product: updatedProduct,
    });

    if (res !== undefined) {
      toast.success("Product successfully updated!");
      setTimeout(() => {
        router.push("/admin/products");
      }, 800);
    }

    setTimeout(() => {
      router.push("/admin/products");
    }, 800);
  };

  useEffect(() => {
    if (error) {
      toast.error("Error fetching product");
    }

    if (updateError) {
      toast.error("Error updating product");
    }
  }, [error, updateError]);

  return (
    <div className="p-4">
      <div className="flex justify-between items-center">
        <h2 className="text-gray-600 font-bold">Edit Product</h2>
      </div>

      <div className="flex justify-between w-100 mt-4">
        <Panel className="mr-4 sm:w-full xl:w-8/12 ">
          {loading ? (
            <LoadingSpinner />
          ) : (
            <ProductForm
              pending={pending}
              product={data?.product}
              onSaveProduct={onEditProduct}
            />
          )}
        </Panel>
      </div>
    </div>
  );
};

const AdminProductsEdit: NextPage = () => {
  const router = useRouter();

  const { id } = router.query as { id?: string };

  if (!id) {
    return null;
  }

  return <Edit id={id} />;
};

(AdminProductsEdit as any).getLayout = function getLayout(page: ReactElement) {
  return <AdminLayout>{page}</AdminLayout>;
};

export default AdminProductsEdit;
