// src/routes/admin/products/new.svelte
<script context="module">
  export const ssr = false;
</script>

<script lang="ts">
  import { writable } from "svelte/store";
  import { goto } from "$app/navigation";
  import { user } from "$lib/stores/user";
  import { notifications } from "$lib/stores/notifications";
  import Panel from "$lib/components/admin/Panel.svelte";
  import ProductForm from "$lib/components/admin/Forms/ProductForm/ProductForm.svelte";
  import { createProduct } from "$lib/components/admin/Forms/ProductForm/helpers";

  let productData = null;
  let pending = false;
  let error = false;

  export let product = writable({
    name: "",
    description: "",
    image: "",
    price: null,
    etsyLink: "",
  });

  product.subscribe((data) => {
    productData = data;
  });

  $: token = $user !== null ? $user.access_token : null;

  async function onCreateProduct() {
    pending = true;
    try {
      await createProduct({ productData, token });

      notifications.success(
        {
          title: "Product Succesfully Created",
          text: "Your product has been sucessfully added",
        },
        3000
      );

      pending = false;
      setTimeout(() => {
        goto("/admin/products");
      }, 500);
    } catch (err) {
      pending = false;
      notifications.danger(
        {
          title: "An error occurred",
          text: "Your product could not be created, please try again later or contact the web admin.",
        },
        5000
      );
    }
  }
</script>

<div class="p-4">
  <div class="flex justify-between items-center">
    <h2 class="text-gray-600 font-bold">Create Product</h2>
  </div>

  <div class="flex justify-between w-100 mt-4">
    <Panel class="mr-4 sm:w-full xl:w-8/12 ">
      <ProductForm {pending} {product} onSaveProduct={onCreateProduct} />
    </Panel>
  </div>
</div>

// pages/admin/products/new.tsx
import { useEffect } from "react";
import { toast } from "react-toastify";
import { useAuth } from "@/contexts/AuthContext";
import { AdminLayout } from "layouts/AdminLayout";
import { ProductForm } from "@/components/admin/Forms/ProductForm";
import { Panel } from "@/components/admin/Panel";
import { useNetlifyPostFunction } from "@/hooks/useNetlifyPostFunction";
import { Product } from "@/types/global";
import { useRouter } from "next/router";
import { NextPageWithLayout } from "@/types/app";

const AdminProductsCreate: NextPageWithLayout = () => {
  const { user } = useAuth();
  const router = useRouter();

  const {
    onCreate,
    pending,
    error: updateError,
  } = useNetlifyPostFunction<{ product: Product }>({ user });

  const onCreateProduct = async (product: Product) => {
    const res = await onCreate(`/admin-products`, { product });

    if (res !== undefined) {
      toast.success("Product successfully added!");
      setTimeout(() => {
        router.push("/admin/products");
      }, 800);
    }
  };

  useEffect(() => {
    if (updateError) {
      toast.error(updateError);
    }
  }, [updateError]);

  return (
    <div className="p-4">
      <div className="flex justify-between items-center">
        <h2 className="text-gray-600 font-bold">Create Product</h2>
      </div>

      <div className="flex justify-between w-100 mt-4">
        <Panel className="mr-4 sm:w-full xl:w-8/12 ">
          <ProductForm pending={pending} onSaveProduct={onCreateProduct} />
        </Panel>
      </div>
    </div>
  );
};

AdminProductsCreate.Layout = AdminLayout;

export async function getStaticProps() {
  return {
    props: {
      protected: true,
    },
  };
}

export default AdminProductsCreate;
