// src/components/admin/Modals/ViewImageModal.tsx
/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import { Modal } from "../Modal";

interface ViewImageModalProps {
  image: string;
  onClose: VoidFunction;
  onWantToDeleteImage: VoidFunction;
}

export const ViewImageModal: React.FC<ViewImageModalProps> = ({
  image,
  onClose,
  onWantToDeleteImage,
}) => {
  return (
    <Modal>
      <div className="w-full flex justify-center">
        <img className="max-w-md" src={image} alt="preview" />
      </div>

      <div className="flex justify-end mt-4">
        <button className="btn-admin" onClick={onClose}>
          {" "}
          Close{" "}
        </button>

        <button
          className="btn-admin btn-danger ml-4"
          onClick={onWantToDeleteImage}
        >
          Delete Image
        </button>
      </div>
    </Modal>
  );
};

// src/lib/components/admin/images/ViewImageModal.svelte
<script>
  import BinIcon from "$lib/components/icons/Bin.svelte";
  import Modal from "$lib/components/admin/Modal.svelte";
  import LoadingSpinner from "$lib/components/shared/LoadingSpinner.svelte";

  export let image = undefined;

  export let onClose = () => {};
  export let onWantToDeleteImage = () => {};
</script>

{#if image}
  <Modal>
    <div class="w-full flex justify-center">
      <img class="max-w-md" src={image} />
    </div>

    <div class="flex justify-end mt-4">
      <button class="btn-admin" on:click={onClose}> Close </button>

      <button class="btn-admin btn-danger ml-4" on:click={onWantToDeleteImage}>
        Delete Image
      </button>
    </div>
  </Modal>
{/if}
