// pages/admin/partners/index.tsx
import type { NextPage } from "next";
import { ReactElement, useEffect } from "react";
import { toast } from "react-toastify";
import { AdminLayout } from "@/layouts/AdminLayout";
import { useAdminIndexFiles } from "@/hooks/useAdminIndexFiles";
import { LoadingSpinner } from "@/components/admin/LoadingSpinner";
import { ImageCard } from "@/components/admin/Cards/ImageCard";
import { ViewImageModal } from "@/components/admin/Modals/ViewImageModal";
import { DeleteImageModal } from "@/components/admin/Modals/DeleteImageModal";
import { UploadImageButton } from "@/components/admin/UploadImageButton";

const AdminPartners: NextPage = () => {
  const {
    files: partners,
    loading,
    onSelectFile: onSelectImage,
    fileSelectedForDetail: partnerSelectedForDetail,
    fileSelectedForRemove: partnerSelectedForRemove,
    onConfirmImageUpload,
    onCancelView,
    onWantToDeleteImage,
    onDeleteSuccess,
    onCancelDelete,
    error,
  } = useAdminIndexFiles<{ partnerLogos: string[] }>({
    fetchUrlPath: "/admin-partners",
    parseResponse: (response) => response.partnerLogos,
  });

  useEffect(() => {
    if (error) {
      toast.error("Error fetching partners");
    }
  }, [error]);

  return (
    <div className="p-4">
      <div className="flex justify-between items-center">
        <h2 className="text-gray-600 font-bold">Partners</h2>
        <UploadImageButton
          actionCopy="Upload New Partner Logo"
          folder="partners_logos"
          onConfirm={onConfirmImageUpload}
        />
      </div>

      <p className="text-gray-600">
        In this section you can manage your Partners. Click on any partner to
        view it in its full size or delete it.
      </p>

      <div className="grid grid-cols-4 gap-4 mt-4">
        {loading ? (
          <LoadingSpinner />
        ) : (
          <>
            {partners.map((partner, index) => (
              <ImageCard
                key={partner}
                image={partner}
                onClick={() => onSelectImage(index)}
              />
            ))}
          </>
        )}
      </div>

      {partnerSelectedForDetail ? (
        <ViewImageModal
          image={partnerSelectedForDetail}
          onClose={onCancelView}
          onWantToDeleteImage={onWantToDeleteImage}
        />
      ) : null}

      {partnerSelectedForRemove ? (
        <DeleteImageModal
          imageToDelete={partnerSelectedForRemove}
          onSuccess={onDeleteSuccess}
          onCancel={onCancelDelete}
        />
      ) : null}
    </div>
  );
};

(AdminPartners as any).Layout = function Layout(page: ReactElement) {
  return <AdminLayout>{page}</AdminLayout>;
};

export default AdminPartners;

// src/routes/admin/partners/index.svelte
<script context="module">
  export const ssr = false;
</script>

<script lang="ts">
  import { onMount } from "svelte";
  import { fetchJson } from "$lib/utils/fetch-json";
  import { user } from "$lib/stores/user";
  import PieChartIcon from "$lib/components/icons/PieChart.svelte";
  import ImageCard from "$lib/components/admin/ImageCard.svelte";
  import LoadingSpinner from "$lib/components/shared/LoadingSpinner.svelte";
  import DeleteImageModal from "$lib/components/admin/images/DeleteImageModal.svelte";
  import ViewImageModal from "$lib/components/admin/images/ViewImageModal.svelte";
  import UploadImageButton from "$lib/components/admin/images/UploadImageButton/index.svelte";

  let selectedPartnerIndex = undefined;
  let partnerToDeleteIndex = undefined;
  let loading = true;

  let partners = [];

  $: token = $user !== null ? $user.access_token : null;

  onMount(async () => {
    const res = await fetchJson("/admin-partners", { token });

    partners = res.partnerLogos;
    loading = false;
  });

  function onConfirmImageUpload(newImage: string) {
    partners = [...partners, newImage];
  }

  function onSelectPartner(index) {
    selectedPartnerIndex = index;
  }

  function onCancelView() {
    selectedPartnerIndex = undefined;
  }

  function onWantToDeletePartner(index) {
    selectedPartnerIndex = undefined;
    partnerToDeleteIndex = index;
  }

  function onDeleteSuccess() {
    partners = [
      ...partners.slice(0, partnerToDeleteIndex),
      ...partners.slice(partnerToDeleteIndex + 1),
    ];

    partnerToDeleteIndex = undefined;
  }

  function onCancelDelete() {
    partnerToDeleteIndex = undefined;
  }
</script>

<div class="p-4">
  <div class="flex justify-between items-center">
    <h2 class="text-gray-600 font-bold">Partners</h2>
    <UploadImageButton
      actionCopy="Add New Partner"
      folder="partners"
      onConfirm={onConfirmImageUpload}
    />
  </div>

  <p class="text-gray-600">
    In this section you can manage your Partners. Click on any image to view it in
    its full size or delete it.
  </p>

  <div class="grid grid-cols-4 gap-4 mt-4">
    {#if loading}
      <LoadingSpinner />
    {/if}

    {#each partners as partner, index}
      <ImageCard image={partner} onClick={() => onSelectPartner(index)} />
    {/each}
  </div>

  {#if selectedPartnerIndex !== undefined}
    <ViewImageModal
      image={partners[selectedPartnerIndex]}
      onClose={onCancelView}
      onWantToDeleteImage={() => onWantToDeletePartner(selectedPartnerIndex)}
    />
  {/if}

  {#if partnerToDeleteIndex !== undefined}
    <DeleteImageModal
      imageToDelete={partners[partnerToDeleteIndex]}
      onCancel={onCancelDelete}
      onSuccess={onDeleteSuccess}
    />
  {/if}
</div>
