// src/lib/components/admin/FormComponents/TextEditor/Editor.svelte
<script>
  import { onMount, onDestroy } from "svelte";
  import { Editor } from "@tiptap/core";
  import StarterKit from "@tiptap/starter-kit";
  import BubbleMenu from "@tiptap/extension-bubble-menu";
  import Menu from "./BubbleMenu.svelte";

  export let content = "";

  let element;
  let editor;

  onMount(() => {
    editor = new Editor({
      element,
      extensions: [
        StarterKit,
        BubbleMenu.configure({
          element: document.querySelector(".bubble-menu"),
        }),
      ],
      content,
      onTransaction: () => {
        editor = editor;
      },
    });

    editor.on("update", ({ editor }) => {
      content = editor.getJSON();
    });
  });

  onDestroy(() => {
    if (editor) {
      editor.destroy();
    }
  });
</script>

<!-- <Menu {editor} /> -->

<div
  class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
>
  <div bind:this={element} />
</div>

// src/components/admin/Editor/index.tsx
import { useEditor, EditorContent } from "@tiptap/react";
import { FieldError } from "react-hook-form";
import StarterKit from "@tiptap/starter-kit";
import BubbleMenuExtension from "@tiptap/extension-bubble-menu";
import { InputErrorMessage } from "../InputErrorMessage";
import { BubbleMenu } from "./BubbleMenu";

interface EditorProps {
  value: string;
  error?: FieldError;
  onChange: (content: string) => void;
  onBlur?: VoidFunction;
}

export const Editor: React.FC<EditorProps> = ({
  value,
  error,
  onChange,
  onBlur,
}) => {
  const editor = useEditor({
    extensions: [
      StarterKit,
      BubbleMenuExtension.configure({
        element: document.querySelector(".bubble-menu") as HTMLElement,
      }),
    ],
    content: value === null || Object.keys(value).length === 0 ? null : value,
    onUpdate({ editor }) {
      onChange(editor.getHTML());
    },
  });

  return (
    <>
      {editor && <BubbleMenu editor={editor} />}

      <div
        className={`editor-container min-h-full h-full shadow appearance-none border ${
          error ? "border-red-500" : ""
        } rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline`}
      >
        <EditorContent editor={editor} onBlur={onBlur} />
      </div>

      {error ? <InputErrorMessage message={error.message || ""} /> : null}
    </>
  );
};
