// src/routes/admin/index.svelte
<script>
  import SummaryCard from "$lib/components/admin/SummaryCard.svelte";
  import { user } from "./store.js";

  let stats = {
    news: 34,
    projects: 13,
    events: 29,
  };

  $: username = $user !== null ? $user.username : null;
</script>

<div class="p-4">
  <h2 class="text-gray-600 font-bold">Welcome back {username}</h2>
  <p class="text-gray-600">
    This is your admin panel, where you can handle everything about events,
    news, projects and images.
  </p>

  <div class="mt-4 w-full grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
    <SummaryCard
      title={`${stats.news} News`}
      link={{ path: "/admin/news", copy: "Manage News" }}
    />
    <SummaryCard
      title={`${stats.projects} Projects`}
      link={{ path: "/admin/projects", copy: "Manage Projects" }}
    />
    <SummaryCard
      title={`${stats.events} Events`}
      link={{ path: "/admin/events", copy: "Manage Events" }}
    />
  </div>
</div>

// pages/admin/index.tsx
import type { NextPage } from "next";
import type { ReactElement } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { useNetlifyGetFunction } from "@/hooks/useNetlifyGetFunction";
import { AdminLayout } from "layouts/AdminLayout";
import { SummaryCard } from "@/components/admin/Cards/SummaryCard";
import { LoadingSpinner } from "@/components/admin/LoadingSpinner";
import { NextPageWithLayout } from "@/types/app";

type Stats = {
  news: number;
  events: number;
  projects: number;
};

const AdminDashboard: NextPageWithLayout = () => {
  const { user } = useAuth();

  const { data, loading, error } = useNetlifyGetFunction<Stats>({
    fetchUrlPath: "/admin-stats",
    user,
  });

  if (loading) {
    return (
      <div className="p-4">
        <LoadingSpinner />
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="p-4">
        <h2>Error fetching your stats, please try again later!</h2>
      </div>
    );
  }

  return (
    <div className="p-4">
      <h2 className="text-gray-600 font-bold">
        Welcome back {user?.user_metadata.full_name}
      </h2>
      <p className="text-gray-600">
        This is your admin panel, where you can handle everything about events,
        news, projects and images.
      </p>

      <div className="mt-4 w-full grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        <SummaryCard
          title={`${data.news} News`}
          link={{ path: "/admin/news", copy: "Manage News" }}
        />

        <SummaryCard
          title={`${data.projects} Projects`}
          link={{ path: "/admin/projects", copy: "Manage Projects" }}
        />

        <SummaryCard
          title={`${data.events} Events`}
          link={{ path: "/admin/events", copy: "Manage Events" }}
        />
      </div>
    </div>
  );
};

AdminDashboard.Layout = AdminLayout;

export async function getStaticProps() {
  return {
    props: {
      protected: true,
    },
  };
}

export default AdminDashboard;
