// pages/admin/schools/[id].tsx
import type { NextPage } from "next";
import { ReactElement, useEffect } from "react";
import { useRouter } from "next/router";
import { toast } from "react-toastify";
import { useAuth } from "@/contexts/AuthContext";
import { AdminLayout } from "layouts/AdminLayout";
import { LoadingSpinner } from "@/components/admin/LoadingSpinner";
import { SchoolForm } from "@/components/admin/Forms/SchoolForm";
import { useNetlifyGetFunction } from "@/hooks/useNetlifyGetFunction";
import { useNetlifyPutFunction } from "@/hooks/useNetlifyPutFunction";
import { Panel } from "@/components/admin/Panel";
import { School } from "@/types/global";

interface EditProps {
  id: string;
}

const Edit: React.FC<EditProps> = ({ id }) => {
  const { user } = useAuth();
  const router = useRouter();

  const { data, loading, error } = useNetlifyGetFunction<{ school: School }>({
    fetchUrlPath: `/admin-schools?id=${id}`,
    user,
  });

  const {
    onUpdate,
    pending,
    error: updateError,
  } = useNetlifyPutFunction<{ school: School }>({ user });

  const onEditSchool = async (updatedSchool: School) => {
    const res = await onUpdate(`/admin-schools?id=${id}`, {
      school: updatedSchool,
    });

    if (res !== undefined) {
      toast.success("School successfully updated");

      setTimeout(() => {
        router.push("/admin/schools");
      }, 800);
    }
  };

  useEffect(() => {
    if (error) {
      toast.error("Error fetching school");
    }

    if (updateError) {
      toast.error("Error updating school");
    }
  }, [error, updateError]);

  return (
    <div className="p-4">
      <div className="flex justify-between items-center">
        <h2 className="text-gray-600 font-bold">Edit School</h2>
      </div>

      <div className="flex justify-between w-100 mt-4">
        <Panel className="mr-4 sm:w-full xl:w-8/12 ">
          {loading ? (
            <LoadingSpinner />
          ) : (
            <SchoolForm
              pending={pending}
              school={data?.school}
              onSaveSchool={onEditSchool}
            />
          )}
        </Panel>
      </div>
    </div>
  );
};

const AdminSchoolsEdit: NextPage = () => {
  const router = useRouter();

  const { id } = router.query as { id?: string };

  if (!id) {
    return null;
  }

  return <Edit id={id} />;
};

(AdminSchoolsEdit as any).Layout = function Layout(page: ReactElement) {
  return <AdminLayout>{page}</AdminLayout>;
};

export default AdminSchoolsEdit;

// src/routes/admin/schools/[id].svelte
<script context="module">
  export const ssr = false;
</script>

<script lang="ts">
  import { page } from "$app/stores";
  import { goto } from "$app/navigation";
  import { fetchJson } from "$lib/utils/fetch-json";
  import { user } from "$lib/stores/user";
  import { onMount } from "svelte";
  import { writable } from "svelte/store";
  import { notifications } from "$lib/stores/notifications";
  import Panel from "$lib/components/admin/Panel.svelte";
  import SchoolForm from "$lib/components/admin/Forms/SchoolForm/SchoolForm.svelte";
  import LoadingSpinner from "$lib/components/shared/LoadingSpinner.svelte";
  import { updateSchool } from "$lib/components/admin/Forms/SchoolForm/helpers";

  let schoolData = null;
  let loading = false; // track the initial load
  let pending = false; // track the school update
  const id = $page.params.id;
  let error = false;

  let school = writable();

  $: token = $user !== null ? $user.access_token : null;

  onMount(async () => {
    const res = await fetchJson(`/admin-schools?id=${id}`, { token });

    school.set(res.school);
    loading = false;
  });

  school.subscribe((data) => {
    schoolData = data;
  });

  async function onSaveSchool() {
    pending = true;
    try {
      await updateSchool({ id, schoolData, status, token });
      notifications.success(
        {
          title: "School Updated",
          text: "Your school has been sucessfully updated!",
        },
        3000
      );

      setTimeout(() => {
        goto("/admin/schools");
      }, 500);
    } catch (err) {
      error = true;
      notifications.danger(
        {
          title: "An error occurred",
          text: "Your school could not be updated, please try again later or contact the web admin.",
        },
        5000
      );
    }

    pending = false;
    school = null;
  }
</script>

<div class="p-4">
  <div class="flex flex-col sm:w-full xl:w-8/12">
    <div class="flex justify-between items-center w-100">
      <h2 class="text-gray-600 font-bold">Update School</h2>
      <a href="/admin/schools" class="text-black">Go Back</a>
    </div>

    <div class="mt-4 w-100">
      {#if loading}
        <LoadingSpinner />
      {:else if schoolData}
        <Panel class="w-100">
          <SchoolForm {pending} {school} {onSaveSchool} />
        </Panel>
      {/if}
    </div>
  </div>
</div>
