// src/lib/components/admin/Sidebar.svelte
<script>
  import CalendarIcon from "$lib/components/icons/Calendar.svelte";
  import ImageIcon from "$lib/components/icons/Image.svelte";
  import NewsIcon from "$lib/components/icons/News.svelte";
  import PieChartIcon from "$lib/components/icons/PieChart.svelte";
  import ProjectsIcon from "$lib/components/icons/Projects.svelte";
</script>

<aside
  id="sidebar"
  class="fixed hidden z-20 h-full top-0 left-0 pt-16 flex lg:flex flex-shrink-0 flex-col w-64 transition-width duration-75"
  aria-label="Sidebar"
>
  <div
    class="relative flex-1 flex flex-col min-h-0 border-r border-gray-200 bg-white pt-0"
  >
    <div class="flex-1 flex flex-col pt-5 pb-4 overflow-y-auto">
      <div class="flex-1 px-3 bg-white divide-y space-y-1">
        <ul class="space-y-2 pb-2">
          <li>
            <a
              href="/admin/"
              class="text-base text-gray-900 font-normal rounded-lg flex items-center p-2 hover:bg-gray-100 group"
            >
              <PieChartIcon />
              <span class="ml-3">Dashboard</span>
            </a>
          </li>
          <li>
            <a
              href="/admin/projects"
              class="text-base text-gray-900 font-normal rounded-lg hover:bg-gray-100 flex items-center p-2 group "
            >
              <ProjectsIcon />
              <span class="ml-3 flex-1 whitespace-nowrap">Projects</span>
            </a>
          </li>
          <li>
            <a
              href="/admin/news"
              class="text-base text-gray-900 font-normal rounded-lg hover:bg-gray-100 flex items-center p-2 group "
            >
              <NewsIcon />
              <span class="ml-3 flex-1 whitespace-nowrap">News</span>
            </a>
          </li>
          <li>
            <a
              href="/admin/events"
              class="text-base text-gray-900 font-normal rounded-lg hover:bg-gray-100 flex items-center p-2 group "
            >
              <CalendarIcon />
              <span class="ml-3 flex-1 whitespace-nowrap">Events</span>
            </a>
          </li>
          <li>
            <a
              href="/admin/images"
              class="text-base text-gray-900 font-normal rounded-lg hover:bg-gray-100 flex items-center p-2 group "
            >
              <ImageIcon />
              <span class="ml-3 flex-1 whitespace-nowrap">Images</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</aside>

// src/layouts/AdminLayout/Sidebar/index.tsx
import { PieChartIcon } from "../../../components/icons/PieChart";
import { ProjectsIcon } from "../../../components/icons/Projects";
import { NewsIcon } from "../../../components/icons/News";
import { CalendarIcon } from "../../../components/icons/Calendar";
import { CartIcon } from "../../../components/icons/Cart";
import { ArchiveIcon } from "../../../components/icons/Archive";
import { LoveIcon } from "../../../components/icons/Love";
import { PeopleIcon } from "../../../components/icons/People";
import { ResearchIcon } from "../../../components/icons/Research";
import { NewspaperIcon } from "../../../components/icons/Newspaper";
import { SchoolIcon } from "../../../components/icons/School";
import { ImageIcon } from "../../../components/icons/Image";
import { DocumentIcon } from "../../../components/icons/Document";
import { SidebarLink } from "./SidebarLink";

export const Sidebar: React.FC = () => (
  <aside
    id="sidebar"
    className="fixed z-20 h-full top-0 left-0 pt-16 flex lg:flex flex-shrink-0 flex-col w-64 transition-width duration-75"
    aria-label="Sidebar"
  >
    <div className="relative flex-1 flex flex-col min-h-0 border-r border-gray-200 bg-white pt-0">
      <div className="flex-1 flex flex-col pt-5 pb-4 overflow-y-auto">
        <div className="flex-1 px-3 bg-white divide-y space-y-1">
          <ul className="space-y-2 pb-2">
            <li>
              <SidebarLink
                href="/admin/"
                label="Dashboard"
                icon={<PieChartIcon />}
              />
            </li>

            <li>
              <SidebarLink
                href="/admin/projects/"
                label="Projects"
                icon={<ProjectsIcon />}
              />
            </li>

            <li>
              <SidebarLink
                href="/admin/news/"
                label="News"
                icon={<NewsIcon />}
              />
            </li>

            <li>
              <SidebarLink
                href="/admin/events/"
                label="Events"
                icon={<CalendarIcon />}
              />
            </li>

            <li>
              <SidebarLink
                href="/admin/products/"
                label="Shop"
                icon={<CartIcon />}
              />
            </li>
          </ul>

          <ul className="py-2">
            <li>
              <SidebarLink
                href="/admin/teaching-resources/"
                label="Teacher Resources"
                icon={<ArchiveIcon />}
              />
            </li>

            <li>
              <SidebarLink
                href="/admin/publications/"
                label="Press & Publications"
                icon={<NewspaperIcon />}
              />
            </li>

            <li>
              <SidebarLink
                href="/admin/research/"
                label="Research"
                icon={<ResearchIcon />}
              />
            </li>
          </ul>

          <ul className="py-2">
            <li>
              <SidebarLink
                href="/admin/trustees/"
                label="Trustees"
                icon={<PeopleIcon />}
              />
            </li>

            <li>
              <SidebarLink
                href="/admin/partners/"
                label="Partners"
                icon={<LoveIcon />}
              />
            </li>

            <li>
              <SidebarLink
                href="/admin/schools/"
                label="Schools"
                icon={<SchoolIcon />}
              />
            </li>
          </ul>

          <ul className="py-2">
            <li>
              <SidebarLink
                href="/admin/files/"
                label="Files"
                icon={<DocumentIcon />}
              />
            </li>

            <li>
              <SidebarLink
                href="/admin/images/"
                label="Images"
                icon={<ImageIcon />}
              />
            </li>
          </ul>
        </div>
      </div>
    </div>
  </aside>
);
