// src/pages/admin/events/new.tsx
import { useEffect } from "react";
import { toast } from "react-toastify";
import { useAuth } from "@/contexts/AuthContext";
import { AdminLayout } from "@/layouts/AdminLayout";
import { EventForm } from "@/components/admin/Forms/EventForm";
import { Panel } from "@/components/admin/Panel";
import { useNetlifyPostFunction } from "@/hooks/useNetlifyPostFunction";
import { Event } from "@/types/global";
import { useRouter } from "next/router";
import { NextPageWithLayout } from "@/types/app";

const AdminEventsCreate: NextPageWithLayout = () => {
  const { user } = useAuth();
  const router = useRouter();

  const {
    onCreate,
    pending,
    error: createError,
  } = useNetlifyPostFunction<{ event: Event; status: "publish" | "draft" }>({
    user,
  });

  const onCreateEvent = async (event: Event, status: "publish" | "draft") => {
    const res = await onCreate(`/admin-events`, { event, status });

    if (res !== undefined) {
      toast.success("Event successfully added!");
      setTimeout(() => {
        router.push("/admin/events");
      }, 800);
    }
  };

  useEffect(() => {
    if (createError) {
      toast.error(createError);
    }
  }, [createError]);

  return (
    <div className="p-4">
      <div className="flex justify-between items-center">
        <h2 className="text-gray-600 font-bold">Create Event</h2>
      </div>

      <div className="flex justify-between w-100 mt-4">
        <Panel className="mr-4 sm:w-full xl:w-8/12 ">
          <EventForm pending={pending} onSaveEvent={onCreateEvent} />
        </Panel>
      </div>
    </div>
  );
};

AdminEventsCreate.Layout = AdminLayout;

export async function getStaticProps() {
  return {
    props: {
      protected: true,
    },
  };
}

export default AdminEventsCreate;

// src/routes/admin/events/new.svelte
<script lang="ts">
  import { writable } from "svelte/store";
  import Panel from "$lib/components/admin/Panel.svelte";
  import EventForm from "$lib/components/admin/Forms/EventForm/EventForm.svelte";
  import { createEvent } from "$lib/components/admin/Forms/EventForm/helpers";

  let eventData = null;
  let pending = false;
  let error = false;

  export let event = writable({
    title: "",
    description: "",
    image: "",
    price: null,
    date: {
      day: "",
      startTime: {
        time: undefined,
        period: "AM",
      },
      endTime: {
        time: undefined,
        period: "AM",
      },
    },
    location: {
      address: {
        addressLine: undefined,
        postcode: undefined,
        city: undefined,
      },
      coordinates: {
        lat: null,
        lng: null,
      },
    },
  });

  event.subscribe((data) => {
    eventData = data;
  });

  async function onSaveEvent(status: "publish" | "draft") {
    pending = true;
    try {
      await createEvent(eventData, "draft");
    } catch (err) {
      error = true;
    }

    pending = false;
    event = null;
  }
</script>

<div class="p-4">
  <div class="flex justify-between items-center">
    <h2 class="text-gray-600 font-bold">Create Event</h2>
  </div>

  <div class="flex justify-between w-100 mt-4">
    <Panel class="mr-4 sm:w-full xl:w-8/12 ">
      <EventForm {pending} {event} {onSaveEvent} />
    </Panel>
  </div>
</div>
