// pages/admin/products/index.tsx
import type { NextPage } from "next";
import { ReactElement, useEffect } from "react";
import { toast } from "react-toastify";
import { AdminLayout } from "layouts/AdminLayout";
import { DeleteItemModal } from "@/components/admin/DeleteItemModal";
import { LoadingSpinner } from "@/components/admin/LoadingSpinner";
import { IndexLayout } from "@/layouts/AdminIndexLayout";
import { ProductCard } from "@/components/admin/Cards/ProductCard";
import { Product } from "@/types/global";
import { useAdminIndexList } from "@/hooks/useAdminIndexList";

const AdminProducts: NextPage = () => {
  const {
    items: products,
    loading,
    error,
    itemToRemoveIndex: productToRemoveIndex,
    onWantToRemoveItem: onWantToRemoveProduct,
    onRemoveConfirmed,
    onRemoveCancelled,
  } = useAdminIndexList<{ products: Product[] }, Product>({
    fetchPath: "/admin-products",
    parseResponse: (response) => response.products,
  });

  useEffect(() => {
    if (error) {
      toast.error("Error fetching products");
    }
  }, [error]);

  return (
    <div className="h-screen bg-admin-grey">
      <div className="flex flex-wrap">
        {loading ? (
          <LoadingSpinner />
        ) : (
          <div className="mt-4 w-full grid grid-cols-1 md:grid-cols-3 xl:grid-cols-4 gap-4">
            {products.map((product, index) => (
              <ProductCard
                key={product._id}
                product={product}
                onWantToRemoveProduct={() => onWantToRemoveProduct(index)}
              />
            ))}
          </div>
        )}
      </div>

      {productToRemoveIndex > -1 ? (
        <DeleteItemModal
          itemGenericName="product"
          itemToDelete={products[productToRemoveIndex]}
          questionItem={products[productToRemoveIndex].name}
          deletePath={`/admin-products?id=${products[productToRemoveIndex]._id}`}
          onSuccess={onRemoveConfirmed}
          onCancel={onRemoveCancelled}
        />
      ) : null}
    </div>
  );
};

(AdminProducts as any).Layout = function Layout(page: ReactElement) {
  return (
    <AdminLayout>
      <IndexLayout
        title="Products"
        subtitle="Here you can manage your products."
        itemName="Product"
        createItemPath="/admin/products/new"
      >
        {page}
      </IndexLayout>
    </AdminLayout>
  );
};

export default AdminProducts;

// src/routes/admin/products/index.svelte
<script context="module">
  export const ssr = false;
</script>

<script lang="ts">
  import LoadingSpinner from "$lib/components/shared/LoadingSpinner.svelte";
  import AdminIndexLayout from "$lib/components/admin/AdminIndexLayout.svelte";
  import ProductCard from "$lib/components/admin/Cards/ProductCard.svelte";
  import DeleteItemModal from "$lib/components/admin/shared/DeleteItemModal.svelte";

  let loading = false;
  let fetchResult = undefined;
  let products = [];
  let productToRemoveIndex = -1;

  function onWantToRemoveProduct(index: number) {
    productToRemoveIndex = index;
  }

  function onRemoveConfirmed() {
    products = [
      ...products.slice(0, productToRemoveIndex),
      ...products.slice(productToRemoveIndex + 1),
    ];
    productToRemoveIndex = -1;
  }

  function onRemoveCancelled() {
    productToRemoveIndex = -1;
  }

  $: {
    if (fetchResult !== undefined) {
      products = fetchResult.products;
    }
  }
</script>

<AdminIndexLayout
  title="Shop"
  subtitle="In this section you can manage all you sellable products."
  itemName="Product"
  fetchUrlPath={"/admin-products"}
  createItemPath={"/admin/products/new"}
  bind:fetchResult
  bind:loading
>
  <div class="flex flex-wrap">
    {#if loading}
      <LoadingSpinner />
    {:else}
      <div
        class="mt-4 w-full grid grid-cols-1 md:grid-cols-3 xl:grid-cols-4 gap-4"
      >
        {#each products as product, index (product._id)}
          <ProductCard
            {product}
            onWantToRemoveProduct={() => onWantToRemoveProduct(index)}
          />
        {/each}
      </div>
    {/if}
  </div>

  {#if productToRemoveIndex > -1}
    <DeleteItemModal
      itemGenericName="product"
      itemToDelete={products[productToRemoveIndex]}
      questionItem={products[productToRemoveIndex].name}
      deletePath={`/admin-products?id=${products[productToRemoveIndex]._id}`}
      onSuccess={onRemoveConfirmed}
      onCancel={onRemoveCancelled}
    />
  {/if}
</AdminIndexLayout>
