// src/pages/admin/trustees/index.tsx
import { useEffect } from "react";
import { toast } from "react-toastify";
import { AdminLayout } from "@/layouts/AdminLayout";
import { DeleteItemModal } from "@/components/admin/DeleteItemModal";
import { LoadingSpinner } from "@/components/admin/LoadingSpinner";
import { IndexLayout } from "@/layouts/AdminIndexLayout";
import { TrusteeCard } from "@/components/admin/Cards/TrusteeCard";
import { Trustee } from "@/types/global";
import { useAdminIndexList } from "@/hooks/useAdminIndexList";
import { NextPageWithLayout } from "@/types/app";

const AdminTrustees: NextPageWithLayout<undefined> =  () => {
  const {
    items: trustees,
    loading,
    error,
    itemToRemoveIndex: trusteeToRemoveIndex,
    onWantToRemoveItem: onWantToRemoveTrustee,
    onRemoveConfirmed,
    onRemoveCancelled,
  } = useAdminIndexList<{ trustees: Trustee[] }, Trustee>({
    fetchPath: "/admin-trustees",
    parseResponse: (response) => response.trustees,
  });

  useEffect(() => {
    if (error) {
      toast.error("Error fetching trustees");
    }
  }, [error]);

  return (
    <div className="h-screen bg-admin-grey">
      <div className="flex flex-wrap">
        {loading ? (
          <LoadingSpinner />
        ) : (
          <div className="mt-4 w-full grid grid-cols-1 md:grid-cols-3 xl:grid-cols-4 gap-4">
            {trustees.map((trustee, index) => (
              <TrusteeCard
                key={trustee._id}
                trustee={trustee}
                onWantToRemoveTrustee={() => onWantToRemoveTrustee(index)}
              />
            ))}
          </div>
        )}
      </div>

      {trusteeToRemoveIndex > -1 ? (
        <DeleteItemModal
          itemGenericName="trustee"
          itemToDelete={trustees[trusteeToRemoveIndex]}
          questionItem={trustees[trusteeToRemoveIndex].name}
          deletePath={`/admin-trustees?id=${trustees[trusteeToRemoveIndex]._id}`}
          onSuccess={onRemoveConfirmed}
          onCancel={onRemoveCancelled}
        />
      ) : null}
    </div>
  );
};

const AdminTrusteesLayout: React.FC = ({ children }) => (
  <AdminLayout>
    <IndexLayout
      title="Trustees"
      subtitle="Here you can manage your trustees."
      itemName="Trustee"
      createItemPath="/admin/trustees/new"
    >
      {children}
    </IndexLayout>
  </AdminLayout>
);

AdminTrustees.Layout = AdminTrusteesLayout;

export async function getStaticProps() {
  return {
    props: {
      protected: true,
    },
  };
}

export default AdminTrustees;

// src/routes/admin/trustees/index.svelte
<script context="module">
  export const ssr = false;
</script>

<script lang="ts">
  import TrusteeCard from "$lib/components/admin/Cards/TrusteeCard.svelte";
  import DeleteItemModal from "$lib/components/admin/shared/DeleteItemModal.svelte";
  import LoadingSpinner from "$lib/components/shared/LoadingSpinner.svelte";
  import AdminIndexLayout from "$lib/components/admin/AdminIndexLayout.svelte";

  let loading = false;
  let fetchResult = undefined;
  let trustees = [];
  let trusteeToRemoveIndex = -1;

  function onWantToRemoveTrustee(index: number) {
    trusteeToRemoveIndex = index;
  }

  function onRemoveConfirmed() {
    trustees = [
      ...trustees.slice(0, trusteeToRemoveIndex),
      ...trustees.slice(trusteeToRemoveIndex + 1),
    ];
    trusteeToRemoveIndex = -1;
  }

  function onRemoveCancelled() {
    trusteeToRemoveIndex = -1;
  }

  $: {
    if (fetchResult !== undefined) {
      trustees = fetchResult.trustees;
    }
  }
</script>

<AdminIndexLayout
  title="Trustees"
  subtitle="In this section you can manage your Trustees."
  itemName="Trustee"
  fetchUrlPath={"/admin-trustees"}
  createItemPath={"/admin/trustees/new"}
  bind:fetchResult
  bind:loading
>
  <div class="flex flex-wrap">
    {#if loading}
      <LoadingSpinner />
    {:else}
      <div
        class="mt-4 w-full grid grid-cols-1 md:grid-cols-3 xl:grid-cols-4 gap-4"
      >
        {#each trustees as trustee, index (trustee._id)}
          <TrusteeCard
            {trustee}
            onWantToRemoveTrustee={() => onWantToRemoveTrustee(index)}
          />
        {/each}
      </div>
    {/if}
  </div>

  {#if trusteeToRemoveIndex > -1}
    <DeleteItemModal
      itemGenericName="trustee"
      itemToDelete={trustees[trusteeToRemoveIndex]}
      questionItem={trustees[trusteeToRemoveIndex].name}
      deletePath={`/admin-trustees?id=${trustees[trusteeToRemoveIndex]._id}`}
      onSuccess={onRemoveConfirmed}
      onCancel={onRemoveCancelled}
    />
  {/if}
</AdminIndexLayout>
