// src/routes/admin/events/index.svelte
<script context="module">
  export const ssr = false;
</script>

<script lang="ts">
  import EventCard from "$lib/components/admin/events/EventCard.svelte";
  import DeleteEventModal from "$lib/components/admin/events/DeleteEventModal.svelte";
  import LoadingSpinner from "$lib/components/shared/LoadingSpinner.svelte";
  import AdminIndexLayout from "$lib/components/admin/AdminIndexLayout.svelte";

  let loading = false;
  let events = [];
  let fetchResult = undefined;
  let eventToRemoveIndex = -1;

  function onWantToRemoveEvent(index: number) {
    eventToRemoveIndex = index;
  }

  function onRemoveConfirmed() {
    events = [
      ...events.slice(0, eventToRemoveIndex),
      ...events.slice(eventToRemoveIndex + 1),
    ];
    eventToRemoveIndex = -1;
  }

  function onRemoveCancelled() {
    eventToRemoveIndex = -1;
  }

  $: {
    if (fetchResult !== undefined) {
      events = fetchResult.events;
    }
  }
</script>

<AdminIndexLayout
  title="Events"
  subtitle="Here you can manage your events."
  itemName="Event"
  fetchUrlPath={"/admin-events"}
  createItemPath={"/admin/events/new"}
  bind:fetchResult
  bind:loading
>
  <div class="flex flex-wrap">
    {#if loading}
      <LoadingSpinner />
    {:else}
      <div
        class="mt-4 w-full grid grid-cols-1 md:grid-cols-3 xl:grid-cols-4 gap-4"
      >
        {#each events as event, index (event._id)}
          <EventCard
            {event}
            onWantToRemoveEvent={() => onWantToRemoveEvent(index)}
          />
        {/each}
      </div>
    {/if}
  </div>

  {#if eventToRemoveIndex > -1}
    <DeleteEventModal
      eventToDelete={events[eventToRemoveIndex]}
      onSuccess={onRemoveConfirmed}
      onCancel={onRemoveCancelled}
    />
  {/if}
</AdminIndexLayout>

// pages/admin/events/index.tsx
import type { NextPage } from "next";
import type { ReactElement } from "react";
import { useEffect } from "react";
import { toast } from "react-toastify";
import { IndexLayout } from "@/layouts/AdminIndexLayout";
import { DeleteItemModal } from "@/components/admin/DeleteItemModal";
// import { AdminLayout } from "@/layouts/AdminLayout";
import { LoadingSpinner } from "@/components/admin/LoadingSpinner";
import { EventCard } from "@/components/admin/Cards/EventCard";
import { Event } from "@/types/global";
import { useAdminIndexList } from "@/hooks/useAdminIndexList";
import { NextPageWithLayout } from "@/types/app";

const AdminEvents: NextPageWithLayout = () => {
  const {
    items: events,
    loading,
    error,
    itemToRemoveIndex: eventToRemoveIndex,
    onWantToRemoveItem: onWantToRemoveEvent,
    onRemoveConfirmed,
    onRemoveCancelled,
  } = useAdminIndexList<{ events: Event[] }, Event>({
    fetchPath: "/admin-events",
    parseResponse: (response) => response.events,
  });

  useEffect(() => {
    if (error) {
      toast.error("Error fetching events");
    }
  }, [error]);

  return (
    <div className="h-screen bg-admin-grey">
      <div className="flex flex-wrap">
        {loading ? (
          <LoadingSpinner />
        ) : (
          <div className="mt-4 w-full grid grid-cols-1 md:grid-cols-3 xl:grid-cols-4 gap-4">
            {events.map((event, index) => (
              <EventCard
                key={event._id}
                event={event}
                onWantToRemoveEvent={() => onWantToRemoveEvent(index)}
              />
            ))}
          </div>
        )}
      </div>

      {eventToRemoveIndex > -1 ? (
        <DeleteItemModal
          itemGenericName="event"
          itemToDelete={events[eventToRemoveIndex]}
          questionItem={events[eventToRemoveIndex].title}
          deletePath={`/admin-events?id=${events[eventToRemoveIndex]._id}`}
          onSuccess={onRemoveConfirmed}
          onCancel={onRemoveCancelled}
        />
      ) : null}
    </div>
  );
};

// (AdminEvents as any).Layout = function Layout(page: ReactElement) {
//   return (
//     <AdminLayout>
//       <IndexLayout
//         title="Events"
//         subtitle="Here you can manage your events."
//         itemName="Event"
//         createItemPath="/admin/events/new"
//       >
//         {page}
//       </IndexLayout>
//     </AdminLayout>
//   );
// };

const AdminEventsLayout: React.FC = ({ children }) => (
  <IndexLayout
    title="Events"
    subtitle="Here you can manage your events."
    itemName="Event"
    createItemPath="/admin/events/new"
  >
    {children}
  </IndexLayout>
);

AdminEvents.Layout = AdminEventsLayout;

export default AdminEvents;
